bs23venv/bs23/urls.py
from django.contrib import admin
from django.urls import path
from meal import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'',include("meal.urls")),
]

bs23venv/meal/urls.py
from meal import views
from django.conf.urls import url
app_name="meal"
urlpatterns =[
    url(r'^menu/',views.menu,name="menu"),
    url(r'^Registration/',views.Registration,name="Registration")
]

bs23venv/meal/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Registrationf(models.Model):
      firstName=models.CharField(max_length=200)
      lastName=models.CharField(max_length=200)
      email=models.EmailField(max_length=200)
      phnNum=models.DecimalField(max_digits=200,decimal_places=10)
      password=models.CharField(max_length=200)

      def _str_(self):
          return self.firstName

bs23venv/meal/views.py
from django.shortcuts import render


from .models import Registrationf


# Create your views here.
def index (request):
    return render(request,"index.html")
def menu (request):
    return render(request,"menu.html")
def Registration(request):
    if request.method == 'POST':
        if request.POST.get('firstName') and request.POST.get('lastName')and request.POST.get('email') and request.POST.get('phnNum')and request.POST.get('password'):
           reg=Registrationf()
           reg.firstName=request.POST.get('firstName')
           reg.lastName = request.POST.get('lastName')
           reg.email= request.POST.get('email')
           reg.phnNum = request.POST.get('phnNum')
           reg.password=request.POST.get('password')
           reg.save()
           return render(request, "Registration.html")
    else:

        return render(request,"Registration.html")

bs23venv/templates/Registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Form</title>
</head>
<body>
   {% block content %}
<form method="POST" action="/Registration/">
     {% csrf_token %}

  First name:<br>
  <input type="text" name="firstName" >
  <br>
    Last name:<br>
  <input type="text" name="lastName" >
  <br>
    Email:<br>
  <input type="text" name="email" >
  <br>
    Phone Number:<br>
  <input type="text" name="phnNum" >
  <br>
    Password:<br>
  <input type="text" name="password" >
  <br><br>
  <input type="submit" value="Submit">
</form>
  {% endblock %}
</body>
</html>

bs23venv/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Brain Staion 23 Mealing system</title>
</head>
<body>
<h1>sakim</h1>
<a href="{% url "meal:menu"%}">next page.</a>
<a href="{% url "meal:Registration"%}">Registration page.</a>
</body>
</html>

bs23venv/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu List</title>
</head>
<body>
<h1>menu</h1>
</body>
</html>